export enum PERMISOSCONSIGNACION {
    crearConsignaciones = "CREAR CONSIGNACIONES",
    consultarComprobados = "CONSULTAR COMPROBADOS",
    consultarAplicados = "CONSULTAR APLICADOS",
    comprobarConsignaciones = "COMPROBAR CONSIGNACIONES",
    aplicarConsignaciones = "APLICAR CONSIGNACIONES",
    editarConsignaciones = "EDITAR CONSIGNACIONES",
    filtrarEstado = "FILTRAR ESTADO",
    filtrarSede = "FILTRAR SEDE",
    filtrarFecha = "FILTRAR FECHA",
    filtrarCedula = "FILTRAR CEDULA",
    generarReportePendientes = "GENERAR REPORTE PENDIENTES",
    generarReportesComprobadas = "GENERAR REPORTES COMPROBADAS",
    generarReporteAplicadas = "GENERAR REPORTE APLICADAS",
    verObservaciones = "VER OBSERVACIONES",
    verComprobante = "VER COMPROBANTE",
    verHistorial = "VER HISTORIAL",
    verReportesGeneral = "VER REPORTES GENERAL",
    verReportesAplicados = "VER REPORTES APLICADOS",
    verReportesComprobados = "VER REPORTES COMPROBADOS",
    verReportesPendientes = "VER REPORTES PENDIENTES",
    filtrarReportesFecha = "FILTRAR REPORTES FECHA",
    filtrarReportesUsuario = "FILTRAR REPORTES USUARIO",
    configuraciones = "CONFIGURACIONES",
    informes = "INFORMES"
}